spring:
  datasource:
    url: jdbc:postgresql://${HOSTNAME}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true


# logging:
#   level:
#     ROOT: TRACE
#     org:
#       hibernate:
#         type:
#           descriptor:
#             sql: trace
